# Generated by Django 6.0.2 on 2026-04-07 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patient_id', models.CharField(max_length=36)),
                ('doctor_id', models.CharField(max_length=36)),
                ('pharmacy_id', models.CharField(blank=True, max_length=36, null=True)),
                ('dispensed_by', models.CharField(blank=True, max_length=36, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('dispensed', 'Dispensed'), ('delivered', 'Delivered')], default='draft', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
