# Generated by Django 6.0.2 on 2026-04-07 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('prescription_id', models.UUIDField(blank=True, null=True)),
                ('prepared_by', models.UUIDField(blank=True, null=True)),
                ('patient_id', models.UUIDField(blank=True, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_address', models.TextField(blank=True, null=True)),
                ('delivery_type', models.CharField(choices=[('pickup', 'Pickup'), ('home_delivery', 'Home Delivery')], default='pickup', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('insurance', 'Insurance'), ('nhif', 'NHIF')], max_length=20, null=True)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=36)),
                ('drug_id', models.CharField(max_length=36)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PDispatchedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=36)),
                ('prescription_id', models.CharField(blank=True, max_length=36, null=True)),
                ('pharmacy_id', models.CharField(blank=True, max_length=36, null=True)),
                ('prescribed_by', models.CharField(blank=True, max_length=36, null=True)),
                ('dispensed_by', models.CharField(blank=True, max_length=36, null=True)),
                ('drug_id', models.CharField(blank=True, max_length=36, null=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('patch', 'Patch'), ('other', 'Other')], max_length=20, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('times_per_day', models.IntegerField(blank=True, null=True)),
                ('dosage_timing', models.JSONField(blank=True, null=True)),
                ('with_food', models.BooleanField(blank=True, default=False, null=True)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'p_dispatched',
                'managed': False,
            },
        ),
    ]
