# Generated by Django 6.0.2 on 2026-04-07 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_number', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=36, unique=True)),
                ('rider_id', models.CharField(blank=True, max_length=36, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('accept_status', models.BooleanField(default=False)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('receiver_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
