# Generated by Django 6.0.2 on 2026-04-07 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pharmacy_id', models.CharField(max_length=36)),
                ('drug_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('chronic', 'Chronic'), ('vitamin', 'Vitamin/Supplement'), ('antifungal', 'Antifungal'), ('other', 'Other')], max_length=50)),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('sachet', 'Sachet'), ('tube', 'Tube')], default='tablet', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=20)),
                ('critical_level', models.IntegerField(default=5)),
                ('requires_rx', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'drugs',
                'ordering': ['drug_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_id', models.CharField(max_length=36)),
                ('supplier_id', models.CharField(blank=True, max_length=36, null=True)),
                ('bulk_order_id', models.CharField(blank=True, max_length=36, null=True)),
                ('received_by', models.CharField(blank=True, max_length=36, null=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity_received', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_batches',
                'ordering': ['expiry_date'],
                'managed': False,
            },
        ),
    ]
